spring.application.name=Ecomerce
server.port=8080
spring.jackson.serialization.indent_output=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
